### ISSUE TITLE
Map File Service

### ISSUE THREAD

**Issue by AnakinRaW** [AlamoEngine-Tools/PetroglyphTools#58]
## User Stories
- [ ] I want to export a map-preview image of a given .ted file and place it to a specified location, so FoC shows planet layouts for land maps.
- [ ] I want to do the map-preview export on a directory level. This way it finds all maps in the given directory and extracts all previews where necessary into a specified location.

### Ted File Service
Since we don't know much about .ted files (yet) and there are no plans for additional file formats to represent maps we can leave the IO Service and Data Model Implementation in one API. The map preview extraction however is still implemented on the data model.

### Map Preview Extration CLI
Since this is the only usecase I can imagek, when working with the map binary files the CLI tool can be named as "Map Preview Extractor". It shall allow users to perform the user stories from above.

**Comment by gruenwaldlk** [comment]
> The map preview extraction however is still implemented on the data model.
That's probably most iomportant part. Even if we figured out, how the maps work, the preview image extractor should not care about all the other data contained.

That also gives me an idea ... Map text IDs tend to mess up, currently you have to clean that by hand with a hex editor, Farseer made a tutorial on how to do that, I don't know much about the map format, but maybe we can automate that cleanup.

And: Just to have that written down somewhere. This issue basically forces two additions: the TED file specific stuff and the basic Chunk file stuff. That has to be separated (which you already did), because then we can re-use the chunk file for the other chunked files: Models, animations, and particles.

**Comment by AnakinSklavenwalker** [comment]
Can you link me to the tutorial?

Also separating map and chunk files was exactly what I was going for. I don't think we have plans for it (nor the need) but it'd allow us to implement an alo viewer in .net
